# Generated by Django 4.0.1 on 2022-01-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calemotion',
        ),
    ]
