# Generated by Django 4.0.1 on 2022-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emo_date', models.DateField()),
                ('positive', models.FloatField(default=0, null=True)),
                ('negative', models.FloatField(default=0, null=True)),
                ('neutral', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'statistics',
                'managed': False,
            },
        ),
    ]
