# Generated by Django 4.0.1 on 2022-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eduser',
            name='username',
            field=models.CharField(default=1, max_length=20, verbose_name='아이디'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eduser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='eduser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
