# Generated by Django 4.0.1 on 2022-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDuser', '0002_remove_eduser_user_id_eduser_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduser',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='eduser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
