# Generated by Django 4.0.1 on 2022-01-23 08:23

import EDuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDuser', '0004_rename_user_eduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=EDuser.models.content_file_name),
        ),
    ]
