# Generated by Django 4.0.1 on 2022-01-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write', models.TextField(verbose_name='일기')),
                ('emotion', models.CharField(max_length=30, verbose_name='감정')),
                ('neutral', models.FloatField(verbose_name='평온')),
                ('positive', models.FloatField(verbose_name='긍정')),
                ('negative', models.FloatField(verbose_name='부정')),
            ],
            options={
                'verbose_name': '일기상세',
                'verbose_name_plural': '일기상세',
                'db_table': 'diary_detail',
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='negative',
            field=models.FloatField(default=1, verbose_name='부정'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='neutral',
            field=models.FloatField(default=1, verbose_name='평온'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='positive',
            field=models.FloatField(default=1, verbose_name='긍정'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(max_length=30, verbose_name='감정'),
        ),
        migrations.CreateModel(
            name='DiaryDetailHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(verbose_name='시작점')),
                ('length', models.IntegerField(verbose_name='길이')),
                ('diary_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diarydetail')),
            ],
            options={
                'verbose_name': '일기상세효과',
                'verbose_name_plural': '일기상세효과',
                'db_table': 'diary_detail_highlight',
            },
        ),
        migrations.AddField(
            model_name='diarydetail',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
        ),
    ]
