# Generated by Django 4.0.1 on 2022-01-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDuser', '0005_alter_eduser_profile_img'),
        ('diary', '0002_diarydetail_diary_negative_diary_neutral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDuser.eduser')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요',
                'db_table': 'expression',
            },
        ),
    ]
