# Generated by Django 4.0.1 on 2022-01-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDuser', '0005_alter_eduser_profile_img'),
        ('diary', '0005_alter_expression_diary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['register_date'], 'verbose_name': '일기', 'verbose_name_plural': '일기'},
        ),
        migrations.AlterField(
            model_name='diary',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDuser.eduser'),
        ),
    ]
