# Generated by Django 4.0.1 on 2022-01-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_diary_register_date'),
        ('diary', '0008_alter_diary_options'),
    ]

    operations = [
    ]
