# Generated by Django 4.0.1 on 2022-01-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_merge_20220127_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
        ),
    ]
