# Generated by Django 4.0.1 on 2022-01-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_merge_20220126_1627'),
        ('diary', '0009_merge_20220127_1544'),
    ]

    operations = [
    ]
