# Generated by Django 4.0.1 on 2022-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_alter_diary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='register_date',
            field=models.DateTimeField(verbose_name='등록날짜'),
        ),
    ]
