# Generated by Django 4.0.1 on 2022-01-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_expression_diary'),
        ('diary', '0012_alter_diary_register_date'),
    ]

    operations = [
    ]
