# Generated by Django 4.0.1 on 2022-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stastics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('emotion1', models.IntegerField()),
                ('emotion2', models.IntegerField()),
                ('emotion3', models.IntegerField()),
            ],
            options={
                'verbose_name': '통계',
                'verbose_name_plural': '통계',
                'db_table': 'stastics',
            },
        ),
    ]
